### ISSUE TITLE
Substitution rule in terms with function symbols

### ISSUE THREAD

**Issue by ionescu** [adamdejl/pithosnd#2]
Hi Adam,

First, thanks for making this.  It's the only open source Fitch style proof-checker I found with support for both function symbols and equality.

I seem to have found a problem with substitution when function symbols are involved.  There is no way to complete the proof

```
1. m = n  given
2. <empty line>
3. f(m) = f(n) goal
```

Selecting ```=sub``` results in an error message.  I have tried introducing ```f(m) = f(m)``` using ```refl``` in order to have the necessary number of lines for ```=sub```, but apparently the system doesn't recognize that ```f(m)``` actually has an ```m``` in it...

Best wishes,
Cezar

**Comment by adamdejl** [comment]
Hello Cezar,

Thank you for your interest in this project as well as for taking the time to report this issue. I have merged a pull request that fixes the logic checking whether a term is contained in a formula. After these changes are deployed, it should be possible to construct the proof using the `refl` rule in the way you described. I am afraid there is currently no rule that could introduce `f(m) = f(n)` based solely on `m = n`. However, I might investigate the possibility of adding such a rule.

**Comment by ionescu** [comment]
Just tried and it works perfectly.  Many thanks!

By the way, I'll be using your project this semester in teaching foundations of computer science ("Grundlagen der Informatik") at the Technische Hochschule Deggendorf (first semester students in the Bachelor in Artificial Intelligence).

Best wishes,
Cezar

**Comment by adamdejl** [comment]
I am glad that you find this project useful for your teaching. Should you or your students encounter any further issues or come up with suggestions on how the application might be improved, please feel free to raise them here.
