### ISSUE TITLE
Problem with disjunction elimination

### ISSUE THREAD

**Issue by ionescu** [adamdejl/pithosnd#4]
Dear Adam,

I can't seem to get vE to work.  For example:

```
1                A ∨ B                given                              
2                B → A               given                              
3                <empty line>                                              
4                A                       <goal>
```

Selecting 1 and 3, and entering "A" as the intended goal, doesn't produce anything.  The two lines remain selected, as does the vE rule.  Selecting 1 and 4 results in the error message "No target (goal or empty) line has been selected.", which is strange, since 4 is obviously a goal line.  

Trying an even simpler example:

```
1     A ∨ A             given
2     <empty line>                                              
3     A                   <goal>
```

Selecting lines 1 and 2 results in the following:

```
An error occured during application of the rule ∨E:

Processing of the proof failed in an unexpected way. Please contact the developer stating the actions that you performed. Sorry... Cause: Failed to extract selected proof line(s).
```

Please let me know if you need additional information.  Thanks for your help!

Best wishes,
Cezar

**Comment by adamdejl** [comment]
Hello Cezar,

Thank you for reporting the issue. I have just merged changes that should resolve the problem.

**Comment by ionescu** [comment]
Wow, that was fast!  Yes, it works now.  Many thanks!
