### ISSUE TITLE
Problem with ⊥I

### ISSUE THREAD

**Issue by ionescu** [adamdejl/pithosnd#6]
Hi,

When trying to apply ⊥I, I get the message "The justification formulas are not a formula and its negation.".  For instance, in the following proof

![bot_intro](https://user-images.githubusercontent.com/2735802/97143515-1d8e5380-1763-11eb-81cc-796235cb78f3.png)

I was selecting lines 2, 5, and 7.  After clicking "OK" I tried again, with the same lines, and it worked.  Same story then after introducing P ∨ ¬P in line 9.  First it doesn't work, then it does.

Sometimes I needed to repeat the selection several times before it worked, and other times it didn't work at all, although all cases were of a formula and its negation.

Many thanks for your help!

Best wishes,
Cezar

**Comment by adamdejl** [comment]
Hello,

Thank you for reporting another issue. This should now be fixed, please don't hesitate to let me know about any other problems you may encounter.

**Comment by ionescu** [comment]
Thanks, it worked perfectly during today's lecture!
